# Configuración del dataset VisDrone-DET2019
path: data/visdrone

train: images/train
val:   images/val
test:  images/test

labels:
  train: labels/train
  val:   labels/val
  test:  labels/test

nc: 10
names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor


#Augmentation

augmentation:
  mosaic: 1.0 # combina 4 imágenes simula alta densidad
  mixup: 0.15 # mezcla imágenes  robustez ante variación visual
  copy_paste: 0.3 # copia objetos minoritarios entre imágenes
  hsv_h: 0.015 # variación de tono  distintas condiciones de luz
  hsv_s: 0.7 # variación de saturación
  hsv_v: 0.4 # variación de brillo simula día/noche
  fliplr: 0.5 # flip horizontal  más perspectivas
  flipud: 0.0 # flip vertical  desactivado en perspectiva aérea
  scale: 0.5 # zoom aleatorio  simula cambios de altitud
  translate: 0.1 # desplazamiento  simula movimiento de cámara
